name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: |
        rustup component add rustfmt
        cargo install cargo-audit
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get update -y
        sudo apt-get install musl-tools -y
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Test
      run: |
        cargo nextest run --verbose
        cargo nextest run --verbose --release

  fmt:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Format
      run: cargo fmt --all -- --check

  security:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Audit
      run: cargo audit
